### ISSUE TITLE
No visual feedback.

### ISSUE THREAD

**Issue by OffifialMITX** [gstraube/cythara#1]
Everything I see is a "b" and a #, a ruler from -30 to +30 and a green mic icon. Might be caused by my small screen since it's only 480p.

**Comment by gstraube** [comment]
Thank you very much for your fast feedback! The same behavior occurs on my phone but only when installing the app through F-Droid (not in development mode). I'm looking into it.

**Comment by gstraube** [comment]
Actually, it seems like it should work. If it isn't too much to ask, could you please play the attached sound files ([sound_files.zip](https://github.com/gstraube/cythara/files/1249768/sound_files.zip)) over your speakers and tell me whether you see any change? It should look something like this:

![e6](https://user-images.githubusercontent.com/4990890/29680157-07285a8c-8904-11e7-8566-b900d4d27bf8.png)

![g3](https://user-images.githubusercontent.com/4990890/29680188-1ca533da-8904-11e7-88af-082dd9b4b59c.png)

**Comment by gstraube** [comment]
There was also an issue with the permissions (the app didn't ask at runtime for the required permission) which you apparently already figured out on your own. Thanks :)! I fixed it but it might take a while for the updated version to appear on F-Droid.

**Comment by OffifialMITX** [comment]
Speaker? Did you mean my microphone? It __did__ ask for 'record audio' permission on my device. I'll report in a few minutes.

**Comment by gstraube** [comment]
It did? That's good to hear :-). I meant the speaker of your notebook or desktop computer (if you happen to be near one and aren't limited to your phone at the moment). Thank you in advance!

**Comment by gstraube** [comment]
The permission issue might have something to do with the Android version. Could you please tell me your version?

**Comment by OffifialMITX** [comment]
I have stock 5.1 / 22 and the sounds you've sent me are plain silence and there's no reaction to those.

On August 24, 2017 7:58:43 PM GMT+02:00, gstraube <notifications@github.com> wrote:
>The permission issue might have something to do with the Android
>version. Could you please tell me your version?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gstraube/cythara/issues/1#issuecomment-324710509

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gstraube** [comment]
Hm, that's strange. If you don't mind, could you please try playing a sound using this site: http://onlinetonegenerator.com/ (with a frequency of e.g. 146 or 110 Hz)?

**Comment by gstraube** [comment]
Hm, that's strange. If you don't mind, could you please try playing a sound using this site: http://onlinetonegenerator.com/ (with a frequency of e.g. 146 or 110 Hz)?

**Comment by OffifialMITX** [comment]
Welp, still no response.

On August 25, 2017 6:09:53 PM GMT+02:00, gstraube <notifications@github.com> wrote:
>Hm, that's strange. If you don't mind, could you please try playing a
>sound using this site: http://onlinetonegenerator.com/ (with a
>frequency of e.g. 146 or 110 Hz)?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gstraube/cythara/issues/1#issuecomment-324965933

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gstraube** [comment]
Thank you! I'll start up an emulator with Android 22 to see what happens.

**Comment by OffifialMITX** [comment]
*(You started the emulator)
*(...)
*(Nothing happened)

On August 25, 2017 6:34:37 PM GMT+02:00, gstraube <notifications@github.com> wrote:
>Thank you! I'll start up an emulator with Android 22 to see what
>happens.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gstraube/cythara/issues/1#issuecomment-324972196

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gstraube** [comment]
I had some trouble with callbacks apparently not being called. Initially, I thought there was some issue with the audio input.
Anyhow, the pitch detection did NOT work in the Android 22 emulator (but it did with the emulator for levels 25 and 26). I'll start debugging.

**Comment by OffifialMITX** [comment]
Practice Hub https://code.google.com/archive/p/music-practice-tools has something similar, maybe that helps.

On August 26, 2017 4:56:45 PM GMT+02:00, gstraube <notifications@github.com> wrote:
>I had some trouble with callbacks apparently not being called.
>Initially, I thought there was some issue with the audio input.
>Anyhow, the pitch detection did NOT work in the Android 22 emulator
>(but it did with the emulator for levels 25 and 26). I'll start
>debugging.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gstraube/cythara/issues/1#issuecomment-325135343

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gstraube** [comment]
Thanks for the link! Their app seems much more advanced :-).

It turns out that a method was depreciated in versions > 23 (https://stackoverflow.com/questions/32077086/android-onattachcontext-not-called-for-api-23) so that the listener fragment could not invoke the callback on the main activity.

I attached an APK to the release page (https://github.com/gstraube/cythara/releases/tag/v1.2) in case you don't want to wait for the F-Droid update.

Thank you very much for your help and patience!

**Comment by OffifialMITX** [comment]
Their app is more advanced, however, it hasn't been updated in years, has the old holo design and most importantly, according to F-Droid, it has security issues. That's why I'm interested in this app.

On August 26, 2017 8:06:18 PM GMT+02:00, gstraube <notifications@github.com> wrote:
>Thanks for the link! Their app seems much more advanced :-).
>
>It turns out that a method was depreciated in versions > 23
>(https://stackoverflow.com/questions/32077086/android-onattachcontext-not-called-for-api-23)
>so that the listener fragment could not invoke the callback on the main
>activity.
>
>I attached an APK to the release page
>(https://github.com/gstraube/cythara/releases/tag/v1.2) in case you
>don't want to wait for the F-Droid update.
>
>Thank you very much for your help and patience!
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gstraube/cythara/issues/1#issuecomment-325152796

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gstraube** [comment]
Seems like at least it could serve as a source of inspiration. However, I can't install it through F-Droid at the moment.

Speaking of which, an update is available through F-Droid but is not the one which contains the fix, although the metadata has already been updated (https://gitlab.com/fdroid/fdroiddata/commit/40fc61e2e6bbe10fa13c09464773ac88c3672b47). I guess it should be available tomorrow or the day after tomorrow.

**Comment by OffifialMITX** [comment]
Cool!

On August 27, 2017 11:23:39 AM GMT+02:00, gstraube <notifications@github.com> wrote:
>Seems like at least it could serve as a source of inspiration. However,
>I can't install it through F-Droid at the moment.
>
>Speaking of which, an update is available through F-Droid but is not
>the one which contains the fix, although the metadata has already been
>updated
>(https://gitlab.com/fdroid/fdroiddata/commit/40fc61e2e6bbe10fa13c09464773ac88c3672b47).
>I guess it should be available tomorrow or the day after tomorrow.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gstraube/cythara/issues/1#issuecomment-325187069

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gstraube** [comment]
The update has been published.

**Comment by OffifialMITX** [comment]
Welp, nothing's changed. Does your app depend on WebView or something?

On August 31, 2017 7:50:38 PM GMT+02:00, gstraube <notifications@github.com> wrote:
>Closed #1.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gstraube/cythara/issues/1#event-1230052128

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gstraube** [comment]
Sorry, I just now saw your message. Did you try the sounds from http://onlinetonegenerator.com/? If possible, could you send me the logging output?

**Comment by OffifialMITX** [comment]
I'll retry the next few days but I van't send any logs unless you make it the app's own feature. :-(

On September 10, 2017 12:17:44 PM GMT+02:00, gstraube <notifications@github.com> wrote:
>Reopened #1.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gstraube/cythara/issues/1#event-1242150371

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gstraube** [comment]
I'll look into that, seems like a good idea. Surely it will be useful in the future :-).

**Comment by gstraube** [comment]
The microphone symbol is now colored green if the app could start recording and remains red otherwise. This should narrow down the cause for the problem.

**Comment by OffifialMITX** [comment]
Okay, now it works for some reason. Whatever you did, thanks!
