### ISSUE TITLE
settings

### ISSUE THREAD

**Issue by bderembl** [gstraube/cythara#11]
Would it be possible to select a "favorite tuner" instead of always having "Guitar (standard)" at startup?
(the same way it works for "set notation" actually)

thanks

**Comment by gstraube** [comment]
Sure, this definitely makes sense! The app could also simply remember the last selection. What do you think about that?

**Comment by bderembl** [comment]
sure: the last selection makes sense
thanks!

**Comment by gstraube** [comment]
Alright! I'll write a comment here once the update has been published on F-Droid.

**Comment by gstraube** [comment]
It has been published.

**Comment by bderembl** [comment]
just tried it.
works great. thanks

**Comment by gstraube** [comment]
Thank you!
