### ISSUE TITLE
f-droid fails with "file not found" for apk

### ISSUE THREAD

**Issue by maphew** [gstraube/cythara#12]
See screenshot, after I figure out how to upload from my phone

![screenshot_20180203-130734](https://user-images.githubusercontent.com/486200/35771554-94b7fd1c-08e3-11e8-9eb8-0f662ec58465.png)

**Comment by gstraube** [comment]
Could you please update the F-Droid repositories (pull down on the "Update" view - see first screenshot) and try again? The current version code is 15, so the URL should be https://f-droid.org/repo/com.github.cythara_15.apk. The status should read "Updated 1 day ago" (see second screenshot).

![screenshot_20180204-205149](https://user-images.githubusercontent.com/4990890/35781668-52953cdc-09ed-11e8-9300-8f575cc58959.png)
![screenshot_20180204-205139](https://user-images.githubusercontent.com/4990890/35781671-5659d77e-09ed-11e8-9451-e66052e03483.png)

**Comment by maphew** [comment]
That worked, thanks! Looking at the repo date didn't occur to me. I though
F-droid checked automatically on startup.

**Comment by gstraube** [comment]
You're welcome! I think the F-Droid client only checks periodically for updates (and even this can be disabled).
