### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by wonea** [gstraube/cythara#13]
I often use this app at night, and would appreciate a dark theme. The light background is a bit harsh on my eyes.

**Comment by gstraube** [comment]
Thanks a lot for your suggestion! A dark theme is definitely useful. I added a couple of screenshots and would like to hear your opinion, especially whether the text color should be dark or light. The theme can be toggled via the action bar menu (see last screenshot).

![screenshot_20180205-182203](https://user-images.githubusercontent.com/4990890/35819575-623bbaec-0aa3-11e8-9412-e48bff652e04.png)
![screenshot_20180205-182206](https://user-images.githubusercontent.com/4990890/35819582-662ac4e0-0aa3-11e8-8953-c59fdfbb0e19.png)
![screenshot_20180205-182208](https://user-images.githubusercontent.com/4990890/35819586-67d3164e-0aa3-11e8-8ddf-b3f10f1badef.png)
![screenshot_20180205-183324](https://user-images.githubusercontent.com/4990890/35819590-69bc6b68-0aa3-11e8-8b40-7dc7d796e341.png)
![screenshot_20180205-183331](https://user-images.githubusercontent.com/4990890/35819592-6b4ffa3a-0aa3-11e8-953c-f0c49c7108ea.png)
![screenshot_20180205-183428](https://user-images.githubusercontent.com/4990890/35819593-6cef575a-0aa3-11e8-9788-87834cbcbfc9.png)

**Comment by wonea** [comment]
Thanks, I like the last one best. Plain white on black. The white on red is also quite nice, but could be better if the white was changed to warmer colour (perhaps more yellowish?).

**Comment by gstraube** [comment]
Thank you for your feedback! The green/red background was supposed to indicate whether the pitch is in tune. Depending on what you think would be most appropriate, we could also drop the green/red background and keep only the dark background.

**Comment by wonea** [comment]
I like the idea of changing background as well. Very intuitive! As long as the transition from black to red/green is nice.

**Comment by gstraube** [comment]
I adjusted the text color to a warm yellow, like you suggested. If this looks reasonable to you, I'll leave it like this and publish it.

![screenshot_20180208-161633](https://user-images.githubusercontent.com/4990890/36074479-aba2eab0-0f40-11e8-8952-a0b4cbf46d42.png)
![screenshot_20180208-165852](https://user-images.githubusercontent.com/4990890/36074480-acbffbc2-0f40-11e8-9dfd-9c0b577f6955.png)
![screenshot_20180208-161618](https://user-images.githubusercontent.com/4990890/36074483-ae41a3b0-0f40-11e8-981e-938b88b6b794.png)

**Comment by wonea** [comment]
Looks fantastic! Look very much forward to tuning my guitar again!

**Comment by gstraube** [comment]
Thank you :-)!

**Comment by gstraube** [comment]
I released the new version (which contains the dark mode as the default display) here and on Google Play. It should be available on F-Droid in a few days.

**Comment by gstraube** [comment]
The new version is now also available on F-Droid.

**Comment by wonea** [comment]
Just got it from F-Droid. Thanks for the update. Looks great!

**Comment by gstraube** [comment]
You're welcome!
