### ISSUE TITLE
set frequency for reference A

### ISSUE THREAD

**Issue by quizilkend** [gstraube/cythara#14]
Hey,
I would love to see an open source guitar tuner, but I'm missing one feature.
I play guitar in a klezmer duo and we have our reference A at 443Hz. Would it be possible to have a setting to set the frequency of the reference A?

**Comment by gstraube** [comment]
Sure, this setting is certainly useful. I'll start working on this.

**Comment by gstraube** [comment]
I added the setting. What do you think would be a reasonable range for the number picker (see screenshot #2)? At the moment, the range is between 300 and 500 Hz but that might be too excessive :-). 

![screenshot_20180211-152304](https://user-images.githubusercontent.com/4990890/36074421-07a88f5a-0f40-11e8-998a-6a55f7b22fdf.png)
![screenshot_20180211-152345](https://user-images.githubusercontent.com/4990890/36074430-0d5f2300-0f40-11e8-89d1-0b78905d04e0.png)
![screenshot_20180211-152358](https://user-images.githubusercontent.com/4990890/36074431-0f1904ae-0f40-11e8-82fc-cdf5c3b31a1f.png)

**Comment by quizilkend** [comment]
Wow, that looks awesome.

Accordiding to the following wikipedia articles, there is a wide range of A4 references.
[https://en.wikipedia.org/wiki/A440_(pitch_standard)](url)
[https://en.wikipedia.org/wiki/Concert_pitch#History_of_pitch_standards_in_Western_music](url)
[https://en.wikipedia.org/wiki/Concert_pitch](url)

They all seem to be in the range of 400Hz to 500Hz, maybe that range is reasonable.

Thank you very much for your work!

**Comment by gstraube** [comment]
You're welcome! Thanks a lot for the research! I adjusted the range and released a new update here and on Google Play. It should be available on F-Droid in a few days.

**Comment by quizilkend** [comment]
Tried it out, it's awesome.

Thank you very much.

**Comment by gstraube** [comment]
Glad to hear that! You're welcome!
