### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by tebriz159** [gstraube/cythara#15]
Hello mate. I saw your project and I think you should change the logo. I can design new logo for your project. If you want please comment below

**Comment by gstraube** [comment]
Sure, I'd appreciate it!

**Comment by gstraube** [comment]
However, it isn't that much of a priority for me (I wouldn't want you to invest too much time). What do you have in mind?

**Comment by tebriz159** [comment]
Okay, I'll try to keep it simple. Thank you for your answer

**Comment by tebriz159** [comment]
I designed the logo, if you like this and want to use in your project, I'll send you all of the original files. I'll wait for your answer )

![logo](https://user-images.githubusercontent.com/31902754/37929611-4a351114-30f5-11e8-9906-f6a380bd17e0.png)
![logo green](https://user-images.githubusercontent.com/31902754/37929617-4d3e68f6-30f5-11e8-8f04-7eeb7bb1d941.png)
![logo with bacgroung](https://user-images.githubusercontent.com/31902754/37929623-50674430-30f5-11e8-9631-77e0558157cd.png)

**Comment by gstraube** [comment]
Sure, it looks really great! I will credit you as a contributor on the README file. Would this be okay for you?

**Comment by tebriz159** [comment]
Yes, it's okay. Editable, monochrome, logotype and all files is here https://drive.google.com/open?id=1FraP235XYZPWpw95i7yTHOFw8aIO-fZx
I added different variations in it. Use which one you like )

**Comment by gstraube** [comment]
The new version containing the logo is now available on both F-Droid and Google Play. Thank you very much for your contribution!

**Comment by tebriz159** [comment]
Thank you ) I posted my work on Utopian https://utopian.io/utopian-io/@tebriz/logo-design-for-cythara
