### ISSUE TITLE
Chromatic mode as standard mode

### ISSUE THREAD

**Issue by TomJansen** [gstraube/cythara#20]
In my experience in using this app, I have found that chromatic mode picks up my guitar strings (normal tuning) way better than Guitar mode and it also works better than Bass mode for basses.

So I would advice setting chromatic mode as default mode (at the top of the list). Chromatic is multi instrumental and works better (in my case at least. It is better than everything else I have used). Setting it as standard would prevent potential users from dismissing the app because it doesn't work on par with other tuners, and that would be a shame because it does.

**Comment by gstraube** [comment]
Thanks a lot for your feedback! Having a particular instrument as the default could also create the impression that the app primarily targets this instrument (while in truth all instruments are treated equally :-)). So I will definitely change it.
