### ISSUE TITLE
Sugestions to a new layout

### ISSUE THREAD

**Issue by thim** [gstraube/cythara#21]
@gstraube I created a fork of the project and I converted the code to Kotlin and changed the interface slightly. I wanted to know your opinion about the new layout.
https://github.com/thim/cythara/tree/kotlin

tks.

**Comment by gstraube** [comment]
Wow, it looks fantastic! I like it very much, thanks a lot! Everything looks very smooth and polished. Marking the tuning selection with a note is a very nice touch :-). I also like the conversion to Kotlin, the package structure and the refactoring. Great job!

Just one small thing: I feel like the wheel scroll for the reference pitch selection is a bit easier to use than the "+" and "-" buttons. Do you prefer it this way or was there maybe a technical reason?

Do you want to open a pull request so we can merge your changes?

**Comment by thim** [comment]
Thanks, glad you like. About the the scroll, I removed all third-party components and I tried to follow the Material Desig guidelines. But I agree with you, I'll look for some better solution, otherwise I'll return the original component.

**Comment by TomJansen** [comment]
Can't you use numberpicker for the scroll? It is a built-in component

**Comment by thim** [comment]
Hum, could be. I think the visual is not so good, but works.

**Comment by thim** [comment]
No problems, I will continue working on my fork. How sad that you lost the key store, I would be happy to publish the app.

**Comment by gstraube** [comment]
Yeah, it's unfortunate but at least it will make sure that next time I include all important files in my backup. Let me know if I can help you in publishing your app!
