### ISSUE TITLE
app crash "ResourcesNotFoundException" on KitKat

### ISSUE THREAD

**Issue by forrestguice** [gstraube/cythara#23]
The app is crashing on launch, "Unfortunately, Cythara has stopped". 

Cythara version 2.9.
My device is running stock api19 (KitKat).

This exception was in the logcat:
```
02-02 13:14:23.394 13168-13168/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.github.cythara, PID: 13168
    android.content.res.Resources$NotFoundException: File res/drawable-nodpi-v4/ic_line_style_icons_mic_active.xml from drawable resource ID #0x7f07005d. If the resource you are trying to use is a vector resource, you may be referencing it in an unsupported way. See AppCompatDelegate.setCompatVectorFromResourcesEnabled() for more info.
        at android.content.res.Resources.loadDrawable(Resources.java:2106)
        at android.content.res.Resources.getDrawable(Resources.java:700)
        at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:465)
        at com.github.cythara.CanvasPainter.drawListeningIndicator(CanvasPainter.java:180)
        at com.github.cythara.CanvasPainter.on(CanvasPainter.java:106)
        at com.github.cythara.TunerView.onDraw(TunerView.java:26)
        at android.view.View.draw(View.java:14465)
```
I suspect its probably something to do with https://stackoverflow.com/questions/37615470/support-library-vectordrawable-resourcesnotfoundexception. I'm not sure at which version it stopped working for me. I was using an older version for a long time, but recently let F-Droid update it.

**Comment by gstraube** [comment]
Thank you reporting this! Could you please try the attached version?
[cythara.zip](https://github.com/gstraube/cythara/files/2825584/cythara.zip)

**Comment by forrestguice** [comment]
The attached version tests ok. Thank you for the speedy fix. :)

**Comment by gstraube** [comment]
You're welcome :-)! I'll release a new version which should be available on F-Droid in a few days (once it has been picked up by the build servers).
