### ISSUE TITLE
Please consider a colorblind mode

### ISSUE THREAD

**Issue by MayeulC** [gstraube/cythara#28]
Some people have trouble distinguishing between red and green. This doesn't afftect me personally, but I know of someone who uses the app and was worried it would affect its effectiveness. Luckily, the scale at the bottom is enough to use it.

**Comment by gstraube** [comment]
This is definitely an important feature. I'll look into what color schemes might be appropriate. Thanks a lot for the feedback!

**Comment by gstraube** [comment]
I decided to add a symbolic indicator which conveys the same information as the red/green background (whether the measured tone is within a certain tolerance range). What do you think? 

![Screenshot_20191110-161656_Cythara](https://user-images.githubusercontent.com/4990890/68546448-8952a180-03d6-11ea-9a28-81eb985e3c06.png)
![Screenshot_20191110-162104_Cythara](https://user-images.githubusercontent.com/4990890/68546449-8952a180-03d6-11ea-9006-d59e69f40cb9.png)
