### ISSUE TITLE
Bass CGCF Tuning

### ISSUE THREAD

**Issue by SiIky** [gstraube/cythara#29]
Hey there, first of all, thanks for publishing this on F-Droid!

I would like to request a new Tuning for Bass, CGCF. Looking at the [Bass Standard Tuning file](https://github.com/gstraube/cythara/blob/f0be3654374b4a75a2ffe67d0172a1eaddc48394/app/src/main/java/com/github/cythara/tuning/BassTuning.java) I think the only thing that needs to change is this:

```java
        C1(C, 1, 32.7),
        G1(G, 1, 49),
        C2(C, 2, 65.41),
        F2(F, 2, 87.31);
```

The frequencies were taken from https://pages.mtu.edu/~suits/notefreqs.html

Thanks in advance if you accept my request! :)

For a copy&paste, I think this would be it, apart maybe from the class name which may not be up to your coding standards:

```java
package com.github.cythara.tuning;

import com.github.cythara.Note;
import com.github.cythara.NoteName;
import com.github.cythara.Tuning;

import static com.github.cythara.NoteName.*;

public class BassCGCFTuning implements Tuning {

    @Override
    public Note[] getNotes() {
        return Pitch.values();
    }

    @Override
    public Note findNote(String name) {
        return Pitch.valueOf(name);
    }

    private enum Pitch implements Note {

        C1(C, 1, 32.7),
        G1(G, 1, 49),
        C2(C, 2, 65.41),
        F2(F, 2, 87.31);

        private final String sign;
        private final int octave;
        private final float frequency;
        private NoteName name;

        Pitch(NoteName name, int octave, float frequency) {
            this.name = name;
            this.octave = octave;
            this.sign = "";
            this.frequency = frequency;
        }

        public NoteName getName() {
            return name;
        }

        public float getFrequency() {
            return frequency;
        }

        @Override
        public int getOctave() {
            return octave;
        }

        @Override
        public String getSign() {
            return sign;
        }
    }
}
```

**Comment by gstraube** [comment]
Hi! Thanks a lot for your suggestion! It looks good to me! Would you be interested in opening a pull request for this since you already did all the work :-)?

**Comment by SiIky** [comment]
Yeah, I don't mind making a PR; I just didn't make one because I can't test... but if you don't mind, I can make one in a bit :)

**Comment by gstraube** [comment]
Thank you! The tuning will appear as "Bass (Drop C)" in the drop-down menu.

**Comment by SiIky** [comment]
Awesome, thanks!
