### ISSUE TITLE
Ukulele support

### ISSUE THREAD

**Issue by samadh** [gstraube/cythara#3]
Currently there's no foss tuner for Ukulele - it will be nice to have in your tuner, making it a Swiss knife for musicians.

**Comment by gstraube** [comment]
Thank you for the suggestion! I'll start working on this.

**Comment by ReportingRaccoon** [comment]
Great Im waiting for ukulele too keep us informed :)

**Comment by gstraube** [comment]
Sure! The changes have been made and the new version should appear soon on F-Droid. I'll leave another comment once the new version has been published there.

**Comment by gstraube** [comment]
The new version has been published.

**Comment by Qwertie-** [comment]
Just got a ukulele today. Found the app on fdroid and it works great. Guess this issue is closed then?

**Comment by gstraube** [comment]
Yes, I'll close it now. I was waiting for feedback, so thank you :-)!
