### ISSUE TITLE
Expert Mode

### ISSUE THREAD

**Issue by SiIky** [gstraube/cythara#32]
Sorry to open yet another issue, but I thought of another feature in the meantime :P

It's certainly nice to choose a tuning and let Cythara help, but what if the tuning you want/need isn't available? (e.g. the CGCF one, until yesterday) 
If the specific tuning you want isn't available, but there is an "Expert Mode", where it shows the closest note currently being played from all the possible notes, the user can still use Cythara to tune.

From a quick look, I think this is how Cythara works: it records the sound of the instrument, and tries to match it to one of the possible notes of the chosen tuning (corresponding to each alternative of the Enum). So a way to implement this is by having an Enum with all the different notes (pretty big list...)

What do you think? Both of the feature and the implementation idea.

**Comment by TomJansen** [comment]
This already exists in Cytara and is called Chromatic tuning.

**Comment by SiIky** [comment]
Oh! I wasn't aware of that... sorry to waste your time then, and thanks for letting me know! :)
