### ISSUE TITLE
Ukulele D tuning does not recognize F# anymore

### ISSUE THREAD

**Issue by transferkraM** [gstraube/cythara#34]
Hey guys,

starting with 3.3 cythara doesn't recognise F# in Ukulele D tuning anymore. Downgrade to 3.2 (with f-droid) solves the issue.

**Comment by gstraube** [comment]
The hard-coded frequencies have been replaced in favor of calculating them which probably causes this issue. I'll look into it. Thank you!

**Comment by gstraube** [comment]
It turns out the tuning was always wrong (F#3 instead of F#4) but the hard-coded frequency was correct. Thanks a lot for pointing this out! A new version should soon be published on F-Droid.

**Comment by transferkraM** [comment]
Sorry for the long delay, confirmed to function properly again. Thank you!, and thank you for that great little app, AND thank you for not f***ing with users and google by using f-droid!

**Comment by gstraube** [comment]
Thank you for the confirmation and your kind words!
