### ISSUE TITLE
Standard pitch A'

### ISSUE THREAD

**Issue by sebo361** [gstraube/cythara#35]
Hi @gstraube , great work with this tuner!

Which standard pitch A' did you use as default setting in this tuner? Usually musicians in an orchestra agree on a standard pitch A' like 443 hz. Others agree on 440 or 442. Is there a possibility to set this before tuning?

**Comment by gstraube** [comment]
Hi @sebo361! The value is indicated in the lower left corner. The default setting is 440 Hz:
![Screenshot_20200729-191024_Cythara](https://user-images.githubusercontent.com/4990890/88831328-76d00080-d1cf-11ea-8d4f-d911e5416b4a.png)

You can also change this value:

![Screenshot_20200729-191030_Cythara](https://user-images.githubusercontent.com/4990890/88831519-c0205000-d1cf-11ea-9f97-cd5ac76cdceb.png)
![Screenshot_20200729-191034_Cythara](https://user-images.githubusercontent.com/4990890/88831534-c31b4080-d1cf-11ea-9a84-c9c324222eec.png)

**Comment by sebo361** [comment]
Cool thank you so much!

**Comment by gstraube** [comment]
You're very welcome!
