### ISSUE TITLE
Tuning for Turkish oud

### ISSUE THREAD

**Issue by romgarb** [gstraube/cythara#36]
Hello, 

I just forked your repository and added support for Turkish oud standard tuning.

It's in the main branch of my fork ([https://github.com/romgarb/cythara](https://github.com/romgarb/cythara)). Shall I do a pull request?

**Comment by gstraube** [comment]
Thank you, that's very cool! Yes, you can open a pull request.

**Comment by romgarb** [comment]
I just did. I couldn't test the changes though, as my laptop can't compile Android apps with Gradle.

**Comment by gstraube** [comment]
No problem, I'll check it out.

**Comment by gstraube** [comment]
The tuning will be included in the next version published on F-Droid (which is also already available here: https://github.com/gstraube/cythara/releases/tag/v3.5). Thanks a lot for your contribution!

**Comment by romgarb** [comment]
I tested the app on my phone and I realized that I made a mistake in the tuning definition. I just opened another PR to fix it. Sorry for the extra work.

**Comment by gstraube** [comment]
No worries, I'll publish a new version with the fix included.

**Comment by gstraube** [comment]
There it is: https://github.com/gstraube/cythara/releases/tag/v3.6

**Comment by romgarb** [comment]
I just tested it, it's working. Thank you for your work!
