### ISSUE TITLE
implement other tunings

### ISSUE THREAD

**Issue by alekksander** [gstraube/cythara#6]
please implement other tunings. now we have ukulele, but even this instrument has a ton of unusual tunings. personally i'd also love to set a demanded note manually (this is good for instance for other string instruments, to practice pitch with wind instruments, or in general to tune anything that is not a guitar). custom set tunings would solve lack of all the tunings in the world :)

**Comment by gstraube** [comment]
I was thinking about adding a chromatic tuner mode which would also address the lack of tunings and allow for tuning a variety of instruments. What's your take on this?

**Comment by alekksander** [comment]
absolutely! can't wait to try it out :)

**Comment by faissaloo** [comment]
It would be really cool if we could add custom tunings, but as for built in ones I really need drop C and drop C#, people will also probably want bass.

**Comment by gstraube** [comment]
Sure, I'll add some additional built-in tunings before tackling the chromatic tuning mode and custom tunings.

**Comment by gstraube** [comment]
Closing this for now -- there is a chromatic tuning mode as well as some in-built tunings.
