### ISSUE TITLE
apk from git won't install

### ISSUE THREAD

**Issue by alekksander** [gstraube/cythara#7]
dunno if it's personal issue, or wider scale, but apk (https://github.com/gstraube/cythara/releases/download/v1.5/cythara.apk) won't install on my phone. it works if installed from f-droid (which i'd like to bypass since You provide .apk's on git)

**Comment by gstraube** [comment]
Sorry about that! Turns out that unsigned APKs cannot be installed. It should work now (with a signed APK).

**Comment by alekksander** [comment]
thanks!
